on:
  workflow_dispatch:
  pull_request:
    paths:
      - "sandbox/karan_rathiya/"
  push:
    branches:
      - main
    paths:
      - "sandbox/karan_rathiya/"

name: dev-sandbox

jobs:
  terraform:
    uses: sukhdeepsingh1/azure-devops-sandbox/.github/workflows/terraform-plan-apply.yml@main
    with:
      TF_WORKING_DIR: "./sandbox/karan_rathiya/"
      TF_VERSION: "1.3.0"
    secrets:
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
